In [27]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder,StandardScaler,MinMaxScaler
from sklearn.metrics import plot_confusion_matrix
from sklearn.neural_network import MLPRegressor,MLPClassifier
import sklearn.model_selection

In [15]:
sensor_data = pd.read_csv(r"C:\Users\ahmzar\Desktop\Mqtt_server\sensor_data_20221117_1019.csv")

In [17]:
sensor_data.shape

(1514, 15)

In [16]:
sensor_data.head()

,Unnamed: 0,_id,Sensor address,sensor_id,humidity,temperature,vdd,waterleak,time,outside temperature (TF),outside relativeHumidity (TF),precipitation (TF),precipitation type (TF),light,motion
0,0,63728011caf3517df237c199,Matsal Addiva Sigurdsgatan,eui-a81758fffe075c91,36,21.9,3624,0.0,"2022/11/14, 18:51:13",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN
1,1,63728011caf3517df237c19a,Pingisrum Addiva Sigurdsgatan,eui-a81758fffe075b65,37,22.2,3629,0.0,"2022/11/14, 18:51:13",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN
2,2,637280a2caf3517df237c19b,Skrivbord Addiva Sigurdsgatan,eui-a81758fffe075b66,36,22.3,3633,0.0,"2022/11/14, 18:53:38",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN
3,3,637280a2caf3517df237c19c,Madelens skrivbord Addiva Sigurdsgatan,eui-a81758fffe075b67,29,25.9,3636,0.0,"2022/11/14, 18:53:38",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN
4,4,6372848c679d686ec9534093,Madelens skrivbord Addiva Sigurdsgatan,eui-a81758fffe075b67,29,25.8,3636,0.0,"2022/11/14, 19:10:20",6.8,98.7,0.0,Ingen nederbörd,NaN,NaN

In [19]:
sensor_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1514 entries, 0 to 1513
Data columns (total 15 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     1514 non-null   int64
 1   _id                            1514 non-null   object
 2   Sensor address                 1514 non-null   object
 3   sensor_id                      1514 non-null   object
 4   humidity                       1514 non-null   int64
 5   temperature                    1514 non-null   float64
 6   vdd                            1514 non-null   int64
 7   waterleak                      1346 non-null   float64
 8   time                           1514 non-null   object
 9   outside temperature (TF)       1514 non-null   float64
 10  outside relativeHumidity (TF)  1514 non-null   float64
 11  precipitation (TF)             1514 non-null   float64
 12  precipitation type (TF)        1514 non-null   object
 13  light                          168 non-null    float64
 14  motion                         168 non-null    float64
dtypes: float64(7), int64(3), object(5)
memory usage: 177.5+ KB

In [23]:
sensor_data['temperature'].unique()

array([21.9, 22.2, 22.3, 25.9, 25.8, 22.1, 22. , 25.7, 25.6, 21.8, 21.5,
       21.6, 21.3, 25.5, 25.4, 21.7, 24.8, 21.4, 23.7, 23.2, 22.4, 22.5,
       22.6, 22.7, 22.8, 22.9, 23. , 23.1])

In [25]:
sensor_data.nunique()

Unnamed: 0                       1514
_id                              1514
Sensor address                      5
sensor_id                           5
humidity                           18
temperature                        28
vdd                                17
waterleak                           1
time                              766
outside temperature (TF)           35
outside relativeHumidity (TF)      89
precipitation (TF)                  1
precipitation type (TF)             3
light                              20
motion                              1
dtype: int64

In [42]:
# Function to check if a string can be converted to a float
def is_convertible(value):
    """
    Checks to see whether a string can be converted to a float.
    Input:
        - A string
    Output:
        - A boolean indicating whether or not the string can be converted to a float
    """
    try:
        float(value)
        return True
    except ValueError:
        return False

    
    
# Initialize list of strings that can't be converted to a float
unconvertibles = []

# Iterate through an array of strings, and append unconvertible strings to a list
str_array = sensor_data['temperature'].to_numpy()
for element in str_array:
    if is_convertible(element) == False:
        unconvertibles.append(element)

# See which strings (if any) are unconvertible
print("Unconvertibles:  ", unconvertibles)
print("Count of unconvertibles:  ", len(unconvertibles))

Unconvertibles:   []
Count of unconvertibles:   0

In [30]:
sensor_data.isnull()

,Unnamed: 0,_id,Sensor address,sensor_id,humidity,temperature,vdd,waterleak,time,outside temperature (TF),outside relativeHumidity (TF),precipitation (TF),precipitation type (TF),light,motion
0,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
3,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1509,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
1510,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
1511,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
1512,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
1513,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True

In [31]:
sensor_data.isna()

,Unnamed: 0,_id,Sensor address,sensor_id,humidity,temperature,vdd,waterleak,time,outside temperature (TF),outside relativeHumidity (TF),precipitation (TF),precipitation type (TF),light,motion
0,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
3,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1509,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
1510,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
1511,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
1512,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
1513,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True

In [35]:
x,y = sensor_data.drop(columns=['temperature']), sensor_data.temperature
x_train , x_test, y_train , y_test = sklearn.model_selection.train_test_split(x,y,test_size=0.2)

In [52]:
# generate the list of categorical and numerical variables
categorical_variables = sensor_data.nunique()[sensor_data.nunique() < 5].keys().to_list()

numerical_variables=list(set(sensor_data.columns) - set(categorical_variables))
categorical_variables.remove('motion')
############################################
categorical_variables = sensor_data.nunique()[sensor_data.nunique() < 5].keys().to_list()

numerical_variables=list(set(sensor_data.columns) - set(categorical_variables))
categorical_variables.remove('motion')

ohe = OneHotEncoder(drop='first', sparse=False)

X_train_ohe = ohe.fit_transform(x_train[categorical_variables])
X_train_ohe_df = pd.DataFrame(X_train_ohe, columns=ohe.get_feature_names(categorical_variables))

# Transform only without fitting
X_test_ohe = ohe.transform(x_test[categorical_variables])
X_test_ohe_df = pd.DataFrame(X_test_ohe, columns=ohe.get_feature_names(categorical_variables))


scaler = StandardScaler()
X_train_sc = scaler.fit_transform(x_train[numerical_variables])
X_train_sc_df = pd.DataFrame(X_train_sc, columns=numerical_variables)

# Transform only without fitting
X_test_sc = scaler.transform(x_test[numerical_variables])
X_test_sc_df = pd.DataFrame(X_test_sc, columns=numerical_variables)

# Merging the transformed dataframe togheter
x_train = pd.merge(X_train_ohe_df, X_train_sc_df, left_index=True, right_index=True)
x_test = pd.merge(X_test_ohe_df, X_test_sc_df, left_index=True, right_index=True)

c:\Users\ahmzar\Desktop\Mqtt_server\env\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
c:\Users\ahmzar\Desktop\Mqtt_server\env\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

KeyError: "['temperature'] not in index"